version: "3.5"

services:
  api:
    image: iyjian/kid-talk-api
    restart: always
    ports:
      - 53005:3000
    env_file:
      - .env
  ui:
    image: iyjian/kid-talk-ui
    restart: always
    env_file:
      - .env    
    ports:
      - 53004:80
